services:
  server:
    image: flwr-server
    ports:
      - "8080:8080"
    networks:
      - flwr_network

  client1:
    image: flwr-client
    volumes:
      - .:/app
      - C:/Users/kskos/PycharmProjects/FLVision/ciciot2023_archive:/app/CICIOTDataset
    working_dir: /app
    depends_on:
      - server
    networks:
      - flwr_network

  client2:
    image: flwr-client
    volumes:
      - .:/app
      - C:/Users/kskos/PycharmProjects/FLVision/ciciot2023_archive:/app/CICIOTDataset
    working_dir: /app
    depends_on:
      - server
    networks:
      - flwr_network

networks:
  flwr_network:
    driver: bridge
